spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_business_assistant
    username: postgres
    password: nadia
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG